spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.50.221:3306
    #username: "zhangac"
    #password: "123456"
    url: jdbc:mysql://123.57.13.132:3306/shop
    username: "shop"
    password: "123456"

server:
  servlet:
    context-path: /shop

mybatis:
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true

pagehelper:
  propertyName: propertyValue
  reasonable: true
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致